<p><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'createindex'),'default', true);?>" title="Create Index">Create Index</a></p>
<p><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'viewindex'),'default', true);?>" title="View Index">View Index</a></p>
<hr />
<p><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'indexpdfs'),'default', true);?>" title="Index PDFs">Index PDFs</a></p>
<hr />
<p><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'search'),'default', true);?>" title="Search">Search</a></p>
<hr />
<p><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'optimize'),'default', true);?>" title="Optimize">Optimize</a></p>
<hr />
<p><a href="<?php echo $this->url(array('controller'=>'pdf', 'action'=>'index'),'default', true);?>" title="PDF Admin">PDF Admin</a></p>